---
- name: TPM2 Dependencies
  hosts: tpm2
  become: true
  
  tasks:
    - name: TPM2 dependencies
      apt:
        name:
          - autoconf-archive
          - libcmocka0
          - libcmocka-dev
          - build-essential
          - git
          - pkg-config
          - gcc
          - g++
          - m4
          - libtool
          - automake
          - libgcrypt20-dev
          - libjson-c-dev
          - autoconf
          - libdbus-glib-1-dev
          - cmake
          - libssl-dev
          - libcurl4-gnutls-dev
          - doxygen
          - uuid-dev
          - efitools
          - tpm2-abrmd
          - tpm2-tools
        state: latest

    - name: glib2.0
      command: apt-get install glib2.0
      args:
        warn: false # apt-get throws a warning about using apt instead. Apt currently does not include glib2.0
      register: apt_result
      changed_when: '"additional disk space" in apt_result.stdout' # Naturally, apt-get always throws a changed result. Checks to see if something was actually getting changed.
